Invalid direction on published tab is fixed in Easel
Pylons-tech/pylons pull request #1083
Opened 2022-09-19 10:21 UTC by faizhashmiRnS

## Description

This PR should fix the bug #1077 .

Now user will be directed to drafts tab if he has saved an NFT to drafts.

2022-09-19 15:15 UTC, kjawadDeveloper2 requested changes
Kindly add tests.

2022-09-21 07:30 UTC, faizhashmiRnS commented
@ahmadrns As per our discussion regarding test cases. Please try to complete it asap.

2022-09-21 17:05 UTC, faddat approved these changes

2022-09-26 15:28 UTC, kjawadDeveloper2 approved these changes

2022-09-26 15:28 UTC, merged