Fixed Buy Button for Free NFT
Pylons-tech/pylons pull request #1144
Opened 2022-09-26 11:41 UTC by faizhashmiRnS

## Description
This PR should fix the issue #1074 .

2022-09-26 15:12 UTC, kjawadDeveloper2 requested changes

2022-09-26 15:16 UTC, StefanB90 commented
@faizhashmiRnS as discussed during standup, please add test cases. Thank you.

2022-09-26 15:20 UTC, kjawadDeveloper2 commented on wallet/lib/pages/purchase_item/purchase_item_screen.dart
> +    if (viewModel.nft.price == "0") {
Solved the issue. @faizhashmiRnS  kindly add tests.

2022-09-27 04:34 UTC, faizhashmiRnS commented on wallet/lib/pages/purchase_item/purchase_item_screen.dart
> +    if (viewModel.nft.price == "0") {
We are setting it to "0" when creating a Recipe in case of FreeDrop.

2022-09-27 14:34 UTC, mustafapylons approved these changes
Looks good to me.

2022-09-27 17:53 UTC, kjawadDeveloper2 commented on wallet/lib/pages/purchase_item/purchase_item_screen.dart
> +    if (viewModel.nft.price == "0") {
we are but anyone can put amount in recipe when they use our sdk.

2022-09-27 18:07 UTC, merged

2022-09-28 09:51 UTC, faizhashmiRnS commented on wallet/lib/pages/purchase_item/purchase_item_screen.dart
> +    if (viewModel.nft.price == "0") {
> we are but anyone can put amount in recipe when they use our sdk.

Got it, Thanks for the correction.