feature: web wallet was added
Pylons-tech/pylons pull request #1145
Opened 2022-09-26 14:47 UTC by faisalnaveedRNS

## Description

web wallet was added
Closes: #XXXX

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2022-09-26 17:53 UTC, kjawadDeveloper2 commented on web-wallet-pylons/@next/components/molecules/history-details/history-details.tsx
> +            <p>{moment(val.createdAt).format('DD/MM/YYYY hh:mm:ss')}</p>
This is the format we are using on the mobileend `MM/dd/yyyy`

2022-09-26 17:54 UTC, kjawadDeveloper2 commented on web-wallet-pylons/@next/components/molecules/media-set/media-set.tsx
> +    } else if (nftType.toLowerCase() === 'pdf') {
'pdf' Can we create constants . As they are used in multi places.

2022-09-26 17:56 UTC, kjawadDeveloper2 commented on web-wallet-pylons/@next/components/organisms/easel-buy-mob-view/easel-buy-mob-view.tsx
> +                    title="OwnerShip"
Can you change spelling from `OwnerShip` to Ownership.

2022-09-26 18:02 UTC, kjawadDeveloper2 requested changes
There are some images in the PR. can we remove this?

2022-09-26 18:02 UTC, kjawadDeveloper2 commented on web-wallet-pylons/@next/store/app.store.ts
> +    // eslint-disable-next-line implicit-arrow-linebreak
Linter issue.

2022-09-26 18:02 UTC, kjawadDeveloper2 commented on web-wallet-pylons/@next/store/slices/auth/auth-api.ts
> +    // eslint-disable-next-line @typescript-eslint/member-delimiter-style
linter.

2022-09-26 18:02 UTC, kjawadDeveloper2 commented on web-wallet-pylons/@next/store/slices/auth/auth.slice.ts
> +/* eslint-disable @typescript-eslint/space-before-function-paren */
linter.

2022-09-26 18:02 UTC, kjawadDeveloper2 commented on web-wallet-pylons/@next/utils/get-blockchain-icon-path.ts
> +    case 'uatom':
Can we make constant.

2022-09-26 18:02 UTC, kjawadDeveloper2 commented on web-wallet-pylons/@next/utils/get-blockchain-icon-path.ts
> +      return ''
Why we have nothing for ujuno?

2022-10-03 12:22 UTC, Kamran95 commented on web-wallet-pylons/@next/hooks/use-axios-fetch.ts
> +  // eslint-disable-next-line consistent-return
Resolved. Some eslint rules are disabled as they might be conflicting with prettier settings

2023-03-01 00:10 UTC, closed without merging