Fixed NFT link in subject of Gmail issue (Recommendation Needed)
Pylons-tech/pylons pull request #1263
Opened 2022-10-17 06:40 UTC by ahmadhassan-dev1

2022-10-17 14:51 UTC, kjawadDeveloper2 requested changes

2022-10-18 04:57 UTC, ahmadrns commented on wallet/ios/Podfile
> +#Override Firebase SDK Version
In iOS, pod files are not installing because of incompatible version of "FirebaseAppCheck" that is why I am overriding "FirebaseSDKVersion".

2022-10-18 04:58 UTC, ahmadrns commented on wallet/ios/Podfile
> +
Removed spaces as during code refactoring spaces added

2022-10-18 05:02 UTC, ahmadrns commented on wallet/ios/Runner.xcodeproj/project.pbxproj
> +		073F87C64C0B4BB8CC13A5C1 /* Pods-Runner.release-development.xcconfig */ = {isa = PBXFileReference; includeInIndex = 1; lastKnownFileType = text.xcconfig; name = "Pods-Runner.release-development.xcc
I was having problem with iOS build, application was not running on iOS so I edited configuration in XCode but that was not an issue so revert code to previous push, that was the issue of "FirebaseSdkVersion".

2022-10-18 05:02 UTC, ahmadrns commented on wallet/lib/services/third_party_services/share_helper.dart
> +      "\n$text",
Yes, It is working as expected.

2022-10-18 15:32 UTC, kjawadDeveloper2 commented on wallet/ios/Podfile
> +#Override Firebase SDK Version
Its working on my side may be because you changed something in the pod file thats why its causing error. Kindly revert.

2022-10-18 15:34 UTC, kjawadDeveloper2 commented
@ahmadrns  there are still three files deleted. Whats the reason?

2022-10-19 05:06 UTC, ahmadrns commented
> @ahmadrns there are still three files deleted. Whats the reason?

Resolved

2022-10-19 14:47 UTC, kjawadDeveloper2 approved these changes

2022-10-19 15:05 UTC, Amean approved these changes

2022-10-19 15:13 UTC, merged