Stop Audio & Video when user taps on share NFT button
Pylons-tech/pylons pull request #1284
Opened 2022-10-21 13:19 UTC by ahmadrns

2022-10-21 15:07 UTC, kjawadDeveloper2 requested changes

2022-10-21 15:07 UTC, kjawadDeveloper2 commented on wallet/lib/pages/detailed_asset_view/owner_view_view_model.dart
> +  void pauseMedia() {
Can you add test for this?

2022-10-24 16:16 UTC, kjawadDeveloper2 commented
There are issue with testing . We should not create video player or audio player. We should use mock repository from the mockito not the one from the mock folder. Using that you should stub values.

2022-10-24 16:18 UTC, kjawadDeveloper2 requested changes

2022-10-24 16:18 UTC, kjawadDeveloper2 commented on wallet/test/mocks/video_player.mocks.dart
> +class MockVideoPlayerController extends _i1.Mock
No need for this.

2022-10-24 16:18 UTC, kjawadDeveloper2 commented on wallet/test/widget_testing/pages/owner_view_screen_test.dart
> +void main() {
@GeneratedMocks([OwnerViewModel]) only this is needed.

2022-10-24 16:18 UTC, kjawadDeveloper2 commented
Kindly also add descriptions.

2022-10-25 04:54 UTC, ahmadrns commented
> There are issue with testing . We should not create video player or audio player. We should use mock repository from the mockito not the one from the mock folder. Using that you should stub values.

Audio & Video have different helper class like `AudioPlayerHelper` & `videoPlayerHelper` which is responsible for playing & pausing media, how can we mock repository to stub the values of `play`,`pause` audio & video

2022-10-25 17:34 UTC, kjawadDeveloper2 commented
> > There are issue with testing . We should not create video player or audio player. We should use mock repository from the mockito not the one from the mock folder. Using that you should stub values.
> 
> Audio & Video have different helper class like `AudioPlayerHelper` & `videoPlayerHelper` which is responsible for playing & pausing media, how can we mock repository to stub the values of `play`,`pause` audio & video

Mock the viewModel not helpers.

2022-10-26 05:44 UTC, ahmadrns commented
> > > There are issue with testing . We should not create video player or audio player. We should use mock repository from the mockito not the one from the mock folder. Using that you should stub values.
> > 
> > 
> > Audio & Video have different helper class like `AudioPlayerHelper` & `videoPlayerHelper` which is responsible for playing & pausing media, how can we mock repository to stub the values of `play`,`pause` audio & video
> 
> Mock the viewModel not helpers.

I have mocked the viewModel itself and not using helper classes in this test case but I didn't deleted it yet as when we have to write test cases for helper classes and we need them. So, can i delete it for now or leave it as it is?

2022-10-27 17:22 UTC, kjawadDeveloper2 commented
> > > > There are issue with testing . We should not create video player or audio player. We should use mock repository from the mockito not the one from the mock folder. Using that you should stub values.
> > > 
> > > 
> > > Audio & Video have different helper class like `AudioPlayerHelper` & `videoPlayerHelper` which is responsible for playing & pausing media, how can we mock repository to stub the values of `play`,`pause` audio & video
> > 
> > 
> > Mock the viewModel not helpers.
> 
> I have mocked the viewModel itself and not using helper classes in this test case but I didn't deleted it yet as when we have to write test cases for helper classes and we need them. So, can i delete it for now or leave it as it is?

Add it then. When its needed.

2022-10-28 17:06 UTC, kjawadDeveloper2 approved these changes

2022-10-28 17:23 UTC, Amean approved these changes

2022-10-28 17:23 UTC, merged