Fix Firebase AppCheck issue
Pylons-tech/pylons pull request #1336
Opened 2022-11-02 12:36 UTC by ahmadrns

Fix Firebase AppCheck issue, Firebase was not providing AppCheck token in debug mode when we use `AndroidProvider.playIntegrity` 

This PR resolve issue https://github.com/Pylons-tech/pylons/issues/1311

2022-11-02 15:29 UTC, kjawadDeveloper2 requested changes

2022-11-02 15:29 UTC, kjawadDeveloper2 commented on wallet/lib/main_prod.dart
> +      const MethodChannel methodChannel = MethodChannel("method-channel");
The method channel must have a proper name.

2022-11-02 15:29 UTC, kjawadDeveloper2 commented
@ahmadrns  what about ios?

2022-11-03 12:26 UTC, ahmadrns commented
> @ahmadrns what about ios?

Added

2022-11-03 17:00 UTC, kjawadDeveloper2 commented
@ahmadrns  its also not working on the android physical device.

2022-11-04 07:13 UTC, faisalnaveedRNS commented
@ahmadrns Please resolve issue,

2022-11-04 07:55 UTC, ahmadrns commented
@kjawadDeveloper2 You will get something like this on your console when you build an application `Enter this debug secret into the allow list in the Firebase Console for your project: 26a77c38-5f8b-4328-abac-e60f15589f17`. just copy and paste this `debug secret` in firebase console and after that when you will make request to firebase appcheck token It will give you actual token.

2022-11-04 15:52 UTC, kjawadDeveloper2 commented
Works for android not for ios. I dont see anything in the logs for registering.

```
Launching lib/main_prod.dart on iPad Pro (12.9-inch) (5th generation) in debug mode...
lib/main_prod.dart:1
Xcode build done.                                           30.1s
remote notifications are not supported in the simulator
Connecting to VM Service at ws://127.0.0.1:58505/3KVNqjdRjTc=/ws
flutter: \^[[90m[🌎 Easy Localization] [DEBUG] Localization initialized<…>
flutter: \^[[90m[🌎 Easy Localization] [DEBUG] Start<…>
flutter: \^[[90m[🌎 Easy Localization] [DEBUG] Init state<…>
flutter: \^[[90m[🌎 Easy Localization] [DEBUG] Build<…>
flutter: \^[[90m[🌎 Easy Localization] [DEBUG] Init Localization Delegate<…>
flutter: \^[[90m[🌎 Easy Localization] [DEBUG] Init provider<…>
flutter: \^[[90m[🌎 Easy Localization] [DEBUG] Load Localization Delegate<…>
flutter: \^[[90m[🌎 Easy Localization] [DEBUG] Load asset from i18n<…>
```

2022-11-04 16:07 UTC, kjawadDeveloper2 approved these changes

2022-11-04 16:07 UTC, Amean approved these changes

2022-11-04 16:07 UTC, merged