Added Splash Screen
Pylons-tech/pylons pull request #1371
Opened 2022-11-10 14:16 UTC by ahmadrns

Solve issue mentioned in https://github.com/Pylons-tech/pylons/issues/1342

2022-11-10 16:01 UTC, kjawadDeveloper2 commented
@ahmadrns  images size is too high Get svg from @StefanB90

2022-11-10 16:05 UTC, kjawadDeveloper2 requested changes

2022-11-10 16:05 UTC, kjawadDeveloper2 commented on wallet/lib/pages/routing_page/splash_screen.dart
> +        setState(() {
Why not value notifier here?

2022-11-10 16:08 UTC, ahmadrns commented
> @ahmadrns images size is too high Get svg from @StefanB90

sure

2022-11-10 16:09 UTC, ahmadrns commented
@StefanB90  @xinyapylons Kindly share `svg` for these images as the size of these images is too high

2022-11-10 16:31 UTC, ahmadrns commented on wallet/lib/pages/routing_page/splash_screen.dart
> +        setState(() {
sure, will refactor it

2022-11-16 16:57 UTC, kjawadDeveloper approved these changes

2022-11-16 17:12 UTC, Amean approved these changes

2022-11-16 18:00 UTC, kjawadDeveloper2 approved these changes

2022-11-16 18:00 UTC, merged