Let's go ahead and merge testapp and the api2 preview now
Pylons-tech/pylons pull request #1380
Opened 2022-11-11 23:53 UTC by afti-githobo

## Description

This pull request adds an (actually working!) Android/iOS* port of testapp, plus an early revision of the new, higher-level Dart API.

Note that the latter sounds big, but it's not actually a breaking change for anything! The high-level API wraps the older, lower-level one; anything that was using the low-level API before will just continue to use it until someone decides to change it.

*_I don't have an iOS environment to work with, don't actually assume it works, someone should probably check it out_

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2022-11-24 16:12 UTC, kjawadDeveloper2 requested changes

2022-11-24 16:13 UTC, kjawadDeveloper2 commented
@afti-githobo  a smaller PR  will be much better option. 

1) A PR for adding a new app. 
2) Another PR for the dart sdk changes. 


and so on.

2022-11-24 16:15 UTC, kjawadDeveloper2 commented
i am going to cherry pick my comments from this PR.

2022-11-25 02:01 UTC, afti-githobo commented on dart_sdk/test/pylons_wallet/pylons_wallet_impl_test.dart
> -import 'package:flutter_test/flutter_test.dart';
cf. https://github.com/Pylons-tech/pylons/issues/1435

2022-11-25 02:03 UTC, afti-githobo commented on dart_sdk/lib/src/pylons_wallet/pylons_wallet_impl.dart
> +  Future<SDKIPCResponse<String>> txExecuteRecipe(
this and the other related change above can be rolled back - they're from when i was experimenting w/ that call before you fixed it

2022-11-25 02:04 UTC, afti-githobo commented on dart_sdk/lib/src/pylons_wallet/pylons_wallet_impl.dart
> +    // TODO: there obviously should not be a hard lock here, figure out wtf is actually up
ipc messages trample each other if sent too quickly in succession. unsure why. hardlock is inelegant but it ducks that issue for a minute.

2022-11-25 02:25 UTC, afti-githobo commented on dart_sdk/lib/src/types/trade.dart
> +// import '../generated/pylons/trade.pb.dart' as generated;
yeah, we never had trade handlers here, this is removed

2022-11-25 02:26 UTC, afti-githobo commented on dart_sdk/lib/src/types/execution.dart
> +//
un-stubbed the execution wrappers

2022-11-25 02:27 UTC, afti-githobo commented on dart_sdk/lib/src/pylons_wallet/pylons_wallet_impl.dart
> +    // TODO: there obviously should not be a hard lock here, figure out wtf is actually up
cf. https://github.com/Pylons-tech/pylons/issues/1433

2022-11-29 19:22 UTC, kjawadDeveloper2 approved these changes

2022-11-30 22:21 UTC, afti-githobo commented
tagging in @faisalnaveedRNS @MikeSofaer @Amean for reviews to get this over the line

2022-11-30 23:15 UTC, merged