WIP update Docker to work against testnet-3
Pylons-tech/pylons pull request #770
Opened 2022-08-09 16:54 UTC by MikeSofaer

## Description

Closes: #XXXX

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] provided a link to the relevant issue or specification
- [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules)
- [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

2022-08-09 19:31 UTC, justyntemme approved these changes
LGTM

2022-08-10 19:40 UTC, mustafapylons approved these changes
Looks good to me.

2022-08-11 01:29 UTC, nghuyenthevinh2000 commented
Uh, no, don't change ENTRYPOINT, it is supposed to work with docker-compose. If you change to CMD then it doesn't work with docker-compose. Using docker-compose is much faster. Just docker-compose up then done.

2022-08-11 01:33 UTC, nghuyenthevinh2000 requested changes

2022-08-11 01:45 UTC, MikeSofaer commented on Dockerfile
> +CMD ["/start.sh"]
I don't want to have to use docker-compose, I think it's good that the container can stand on its own. Why do you prefer compose here? This is a single container and I don't think compose is adding anything here.

I think it's fine to use entrypoint, though, although I'm not clear on why CMD won't work.

2022-08-11 02:01 UTC, MikeSofaer commented on Dockerfile
> +CMD ["/start.sh"]
thinking about it more, I'm worried that entrypoint here will make getting a shell on the machine impossible because the script execs the node.

2022-08-11 02:40 UTC, nghuyenthevinh2000 commented on Dockerfile
> +CMD ["/start.sh"]
with one command: docker-compose up -d does the follwing:

1. build image
2. run container
3. run script
4. expose port

It is much more convinient than running multiple docker commands

2022-08-11 02:42 UTC, nghuyenthevinh2000 commented on Dockerfile
> +CMD ["/start.sh"]
I just add the code and it works fine

2022-08-11 02:42 UTC, MikeSofaer commented on Dockerfile
> +CMD ["/start.sh"]
It's slightly more convenient, but I don't think you are correct about ENTRYPOINT. It should not be necessary to rely on docker-compose for the container to function correctly. I will make sure that it works, though!

2022-08-11 02:43 UTC, nghuyenthevinh2000 commented on Dockerfile
> +CMD ["/start.sh"]
![Screenshot from 2022-08-11 09-42-44](https://user-images.githubusercontent.com/23058164/184056311-db182c60-f0aa-4c3e-95d6-2f3a6d8a02f1.png)

2022-08-11 02:43 UTC, MikeSofaer commented on Dockerfile
> +CMD ["/start.sh"]
I'm actually experimenting with adding the trace logger to the compose script now.

2022-08-11 03:14 UTC, MikeSofaer commented
docker-compose works fine without needing the command override in the compose file.

This PR also adds another container that spits out all transactions, so we should disable that before we merge, I was just experimenting and this is going to be awesome.

2022-08-12 02:38 UTC, nghuyenthevinh2000 approved these changes

2022-08-12 13:34 UTC, merged